### ISSUE TITLE
SAVE button on the screen dish 7 overlaps the description field

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#147]
**Build version:**
1.0.159

**Severity:**
Low;

**Description:**
SAVE button a little bit overlaps the description field if it filled with the maximum amount of characters (or like in my testing environment it starting overlaps after 5th row in the description field).

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1. Create the dish;
2. Open dish 7 screen of the created dish;
3. Enter text no less than 5 rows in the description field ;

**Actual result:** SAVE button overlaps on the description field;
**Expected result:** SAVE button doesn't overlap on the description field. There should be some free space between the button and the field.

**Walkaround:**

**Attachments:**
![Screenshot_1](https://user-images.githubusercontent.com/45947708/55287582-91b01c00-53b3-11e9-9bea-a4f3ca24d486.png)

**Comment by ordeh** [comment]
@YuryiDasevich , good job, I have been fixed this.

Fixed in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23485055

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23485055/artifacts

![изображение](https://user-images.githubusercontent.com/25455982/55287825-c7a2cf80-53b6-11e9-8c7d-3aedf983e1f4.png)

**Comment by YuryiDasevich** [comment]
Verified.
