### ISSUE TITLE
Values from the drop-down list are not visible [Ingredient 2]

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#154]
**Build version:**
1.0.183

**Severity:**
Medium;

**Description:**
You can not see values of Weight Unit ddl  on the ingredient 2 screen;

_Note:_ if you click on some place in this list the value will be chosen and will be correctly displayed in the field Weight Unit

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1. Start creating an ingredient (open ingredient 2 screen)
2. Tap on weight unit ddl;

**Actual result:** all values unreadable (painted white);
**Expected result:** you can see all available values from the ddl;

**Attachments:**

![Screenshot_1](https://user-images.githubusercontent.com/45947708/55683065-2088df80-5944-11e9-9929-efab5a084385.png)

**Comment by ordeh** [comment]
Fixed in build: 
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23658623

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23658623/artifacts

@YuryiDasevich , 
You can note that the color of a line under drop-down list different from other colors, I cannot fix this.

I can return white color in line under drop-down list but we get this bug again.

I think that we can keep my way, it is better solutions in the current case.

I can suggest create new bug for different line color. Please create new bug with low priority if you agree with me.

![изображение](https://user-images.githubusercontent.com/25455982/55684231-8a5bb600-5951-11e9-838c-d45a49bdb458.png)


![изображение](https://user-images.githubusercontent.com/25455982/55684227-85970200-5951-11e9-81b7-01aeca4e392a.png)

**Comment by YuryiDasevich** [comment]
OK @ordeh , I agree with you about this.
New bug - #161
